import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "var(--inverse-surface)",
        "outline-variant": "var(--outline-variant)",
        "on-tertiary": "var(--on-tertiary)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        primary: "var(--primary)",
        "on-surface-variant": "var(--on-surface-variant)",
        surface: "var(--surface)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-error": "var(--on-error)",
        "surface-container": "var(--surface-container)",
        "error-container": "var(--error-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "primary-fixed": "var(--primary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-background": "var(--on-background)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "primary-container": "var(--primary-container)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-primary-container": "var(--on-primary-container)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-tint": "var(--surface-tint)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-primary": "var(--on-primary)",
        "surface-container-low": "var(--surface-container-low)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-container-high": "var(--surface-container-high)",
        "on-error-container": "var(--on-error-container)",
        secondary: "var(--secondary)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        background: "var(--background)",
        "on-secondary-container": "var(--on-secondary-container)",
        outline: "var(--outline)",
        error: "var(--error)",
        "secondary-container": "var(--secondary-container)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "surface-dim": "var(--surface-dim)",
        "on-surface": "var(--on-surface)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-variant": "var(--surface-variant)",
        "surface-bright": "var(--surface-bright)",
        "on-secondary": "var(--on-secondary)",
        tertiary: "var(--tertiary)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        lg: "24px",
        xl: "32px",
        sm: "8px",
        xs: "4px",
        gutter: "16px",
        md: "16px",
        "container-margin": "24px",
      },
      fontFamily: {
        h1: ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "data-tabular": ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        h3: ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
};
export default config;
