import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';

const read = (file) => readFileSync(path.resolve(file), 'utf8');
const edge = read('supabase/functions/traffic-report/index.ts');
const config = read('supabase/config.toml');
const migration = read('supabase/migrations/20260822090000_public_traffic_report_v1.sql');
const phase23Migration = read('supabase/migrations/20260822150000_public_traffic_report_phase23.sql');
const operationalV2Migration = read('supabase/migrations/20260829130000_public_traffic_report_operational_v2.sql');
const canonicalSourceMigration = read('supabase/migrations/20260829173000_public_traffic_report_canonical_source.sql');
const paxPresenceMigration = read('supabase/migrations/20260829210000_public_traffic_report_pax_presence_contract.sql');
const aircraftTypeMigration = read('supabase/migrations/20260830200000_public_traffic_report_aircraft_type_contract.sql');
const regularFlightsMigration = read('supabase/migrations/20260831120000_public_traffic_report_regular_flights.sql');
const annualKpiMigration = read('supabase/migrations/20260831150000_public_annual_passenger_kpi.sql');
const annualKpiOwnerMigration = read('supabase/migrations/20260831190000_annual_passenger_kpi_owner.sql');
const liveCandidateSliceMigration = read('supabase/migrations/20260831205000_public_traffic_candidate_slice_v1.sql');
const liveAggregateV2Migration = read('supabase/migrations/20260831210000_public_traffic_live_aggregate_v2.sql');
const nginx = read('../deploy/traffic-report/nginx.conf');
const stagingNginx = read('../deploy/traffic-report/nginx-staging.conf');
const stagingTunnel = read('../deploy/traffic-report/seasonal-traffic-report-staging-tunnel.service');
const refreshTimer = read('../deploy/traffic-report/seasonal-traffic-report-refresh.timer');
const productionRefreshTimer = read('../deploy/traffic-report/seasonal-traffic-report-refresh-production.timer');
const refreshService = read('../deploy/traffic-report/seasonal-traffic-report-refresh.service');
const refreshRunner = read('../deploy/traffic-report/seasonal-traffic-report-refresh');
const manualRefresh = read('../deploy/traffic-report/seasonal-traffic-report-refresh-manual');
const deployRunbook = read('../docs/runbooks/public-traffic-report-deploy.md');
const reportOnlyBuild = read('scripts/build-traffic-report-only.mjs');
const packageJson = read('package.json');

assert.match(config, /\[functions\.traffic-report\]\s*verify_jwt = false/);
assert.match(edge, /request\.method !== 'GET'/);
assert.match(edge, /SUPABASE_REST_URL/);
assert.match(edge, /unsupported query parameter/);
assert.match(edge, /duplicate scalar parameter/);
assert.match(edge, /status: 308/);
assert.match(edge, /`\/api\/report\/\$\{isV2 \? 'v2' : 'v1'\}\/\$\{endpoint\}/);
assert.match(edge, /'Cache-Control': 'no-store'/);
assert.doesNotMatch(edge, /request\.headers\.get\(['"]Authorization/);
assert.match(edge, /get_public_traffic_report_overview_v1/);
assert.match(edge, /get_public_traffic_report_v2/);
assert.match(edge, /expected_watermark/);
assert.match(edge, /DATA_VERSION_CHANGED/);
assert.match(edge, /status: 304/);
assert.match(edge, /X-Report-Source-Mode/);
assert.match(edge, /query: normalized\.canonicalQuery/);
assert.match(edge, /next_cursor/);
assert.match(edge, /get_public_traffic_report_dimension_v2/);
assert.match(edge, /dimension-export/);
assert.match(edge, /endpoint === 'dimension' \|\| endpoint === 'dimension-export'/);
assert.match(edge, /allRows\.sort/);
assert.match(edge, /buildDimensionCsv\(responsePayload\)/);
assert.match(edge, /source_watermark: bundle\.source_watermark/);
assert.match(edge, /dimensionDataAsOf = typeof dimensionPayload\.data_as_of === 'string'/);
assert.match(edge, /dimensionArgs\(normalized, page, dimensionDataAsOf\)/);
assert.match(edge, /data_as_of: dimensionDataAsOf/);
assert.match(edge, /REPORT_TEMPORARILY_UNAVAILABLE/);
assert.doesNotMatch(edge, /postgrestRpc\('get_traffic_report_timeline'/);
assert.doesNotMatch(edge, /postgrestRpc\('get_traffic_report_breakdowns'/);
assert.doesNotMatch(edge, /'Accept-Profile'/);
assert.match(edge, /max-age=0, s-maxage=60, stale-while-revalidate=30/);
assert.match(edge, /get_public_annual_passenger_kpi_v1/);
assert.match(edge, /get_public_annual_passenger_kpi_version_v1/);
assert.match(edge, /ANNUAL_KPI_ADMIN_PIN_HASH/);
assert.match(edge, /pbkdf2_sha256/);
assert.match(edge, /HttpOnly; Secure; SameSite=Strict/);
assert.match(edge, /sessionCookie\('locked', 1\)/);
assert.doesNotMatch(edge, /sessionCookie\([^\n]+, 0\)/);
assert.match(edge, /await discardRequestBody\(request\)/);
assert.match(edge, /config: saved, snapshot/);
assert.match(edge, /endpoint === 'kpi-config'[\s\S]+?'no-store'/);
assert.match(edge, /KPI_ADMIN_MAX_FAILURES = 5/);
assert.match(edge, /request\.headers\.get\('Origin'\)/);
assert.match(edge, /If-None-Match/);

assert.match(annualKpiMigration, /create table if not exists reporting\.annual_passenger_kpis/);
assert.match(annualKpiMigration, /revoke all on reporting\.annual_passenger_kpis from public, anon, authenticated, service_role/);
assert.match(annualKpiMigration, /values \(2026, 7500000\)/);
assert.match(annualKpiMigration, /get_public_annual_passenger_kpi_v1/);
assert.match(annualKpiMigration, /published projection version/);
assert.doesNotMatch(annualKpiMigration, /'current_watermark'/);
assert.match(annualKpiMigration, /ops_date between v_year_start and v_period_end/);
assert.match(annualKpiMigration, /pax is not null/);
assert.match(annualKpiMigration, /v_coverage >= 99\.5/);
assert.match(annualKpiMigration, /v_elapsed_days >= 28/);
assert.match(annualKpiMigration, /ceil\(\(v_target - v_reported_pax\)::numeric \/ v_remaining_days\)/);
assert.match(annualKpiMigration, /when v_forecast_pct > 102 then 'ahead'/);
assert.match(annualKpiMigration, /when v_forecast_pct >= 98 then 'on_track'/);
assert.match(annualKpiMigration, /revoke execute[\s\S]+from public, anon, authenticated/);
assert.match(annualKpiOwnerMigration, /alter table reporting\.annual_passenger_kpis owner to postgres/);
assert.match(annualKpiOwnerMigration, /revoke all on reporting\.annual_passenger_kpis[\s\S]+service_role/);
assert.match(liveCandidateSliceMigration, /public\.is_canonical_flight_leg_active_v1\(records\.status, records\.action\)/);
assert.match(liveCandidateSliceMigration, /coalesce\(modifications\.action, 'modified'\) <> 'deleted'/);
assert.match(liveCandidateSliceMigration, /records\.operational_date between p_from_date::text and p_to_date::text/);
assert.match(liveCandidateSliceMigration, /coalesce\(entity_recency\.server_seq, season_recency\.server_seq\)/);
assert.match(liveCandidateSliceMigration, /revoke execute[\s\S]+public, anon, authenticated, service_role/);
assert.match(liveCandidateSliceMigration, /get_public_traffic_canonical_bounds_v1/);
assert.doesNotMatch(liveCandidateSliceMigration, /from reporting\.public_traffic_candidates/i);
assert.match(liveAggregateV2Migration, /from reporting\.get_public_traffic_candidate_slice_v1\(/);
assert.match(liveAggregateV2Migration, /from reporting\.get_public_traffic_canonical_bounds_v1\(\)/);
assert.match(liveAggregateV2Migration, /v_scan_from - 1,[\s\S]+v_scan_to \+ 1/);
assert.match(liveAggregateV2Migration, /effective_action is distinct from 'deleted'/);
assert.match(liveAggregateV2Migration, /candidate_rank = 1/);
assert.match(liveAggregateV2Migration, /DATA_VERSION_CHANGED/);
assert.match(liveAggregateV2Migration, /pax is not null/);
assert.match(liveAggregateV2Migration, /pax = 0/);
assert.match(liveAggregateV2Migration, /generate_series\(v_from_date, v_to_date/);
assert.match(liveAggregateV2Migration, /revoke execute[\s\S]+public, anon, authenticated, service_role/);
assert.match(liveAggregateV2Migration, /grant execute[\s\S]+to service_role/);
assert.doesNotMatch(liveAggregateV2Migration, /from public\.season_flight_records/i);
assert.doesNotMatch(liveAggregateV2Migration, /from reporting\.public_traffic_effective/i);
assert.doesNotMatch(liveAggregateV2Migration, /from reporting\.public_traffic_ranked_candidates/i);

for (const signature of [
  'reporting.get_traffic_report_kpis',
  'reporting.get_traffic_report_timeline',
  'reporting.get_traffic_report_breakdowns',
  'public.get_public_traffic_report_overview_v1',
  'reporting.get_traffic_report_timeline_v2',
  'reporting.get_traffic_report_monthly_peaks_v2',
  'public.get_public_traffic_report_dimension_v2',
]) {
  assert.ok(`${migration}\n${phase23Migration}\n${operationalV2Migration}`.includes(signature), `migration is missing ${signature}`);
}
assert.match(operationalV2Migration, /public_traffic_coverage/);
assert.match(operationalV2Migration, /when grouped\.flights is not null then grouped\.flights when coverage\.coverage_status = 'complete' then 0/);
assert.match(operationalV2Migration, /'pax_coverage_pct'/);
assert.match(operationalV2Migration, /'flight_share'/);
assert.match(operationalV2Migration, /'pax_share'/);
assert.match(canonicalSourceMigration, /public_traffic_projection_state/);
assert.match(canonicalSourceMigration, /snapshot_source_watermark/);
assert.match(canonicalSourceMigration, /snapshot_rows/);
assert.match(canonicalSourceMigration, /get_public_traffic_report_overview_canonical_base_v1/);
assert.match(paxPresenceMigration, /only NULL means/i);
assert.match(paxPresenceMigration, /pax is not null/);
assert.match(aircraftTypeMigration, /get_traffic_report_aircraft_types_v1/);
assert.match(aircraftTypeMigration, /20260830193000_public_traffic_aircraft_type_snapshot\.sql/);
assert.match(aircraftTypeMigration, /from reporting\.public_traffic_effective operations/);
assert.doesNotMatch(aircraftTypeMigration, /join reporting\.public_traffic_ranked_candidates/i);
assert.match(aircraftTypeMigration, /\{breakdowns,aircraft_type\}/);
assert.match(aircraftTypeMigration, /'share'/);
assert.match(aircraftTypeMigration, /reported_legs[^]*reported_pax/);
assert.match(aircraftTypeMigration, /arrival_reported_pax/);
assert.match(aircraftTypeMigration, /departure_reported_pax/);
assert.match(aircraftTypeMigration, /get_traffic_report_timeline_operational_base_v2/);
assert.match(aircraftTypeMigration, /get_public_traffic_report_dimension_operational_base_v2/);
assert.match(aircraftTypeMigration, /alter function public\.get_public_traffic_report_overview_canonical_base_v1\([\s\S]+?\) owner to postgres;/);
assert.match(aircraftTypeMigration, /flight_primary/);
assert.match(aircraftTypeMigration, /pax_primary/);
assert.match(aircraftTypeMigration, /v_effective_as_of/);
assert.match(aircraftTypeMigration, /scheduled_local_at \+ interval '1 day'[^]*p_data_as_of/);
assert.doesNotMatch(aircraftTypeMigration, /drop\s+materialized\s+view/i);
assert.doesNotMatch(aircraftTypeMigration, /coalesce\s*\(\s*operations\.pax\s*,\s*0\s*\)/i);
assert.match(regularFlightsMigration, /regular_flights/);
assert.match(regularFlightsMigration, /occurrence_days >= 4/);
assert.match(regularFlightsMigration, />= 0\.70/);
assert.match(regularFlightsMigration, /split_part\(business_leg_key, chr\(31\), 4\)/);
assert.doesNotMatch(regularFlightsMigration, /record_id/);
assert.doesNotMatch(regularFlightsMigration, /create\s+(materialized\s+)?view/i);
assert.match(phase23Migration, /'day_of_week'/);
assert.match(phase23Migration, /'filter_options'/);
assert.match(phase23Migration, /generate_series\(0, \(1440 \/ p_bucket_minutes\) - 1\)/);
assert.match(migration, /revoke execute[\s\S]+from public, anon, authenticated/);
assert.match(migration, /grant execute on function public\.get_public_traffic_report_overview_v1[\s\S]+to service_role/);
assert.match(migration, /effective_action is distinct from 'deleted'/);
assert.match(migration, /public_traffic_duplicate_quarantine/);
assert.match(migration, /generate_series/);
assert.match(migration, /set statement_timeout = '7s'/);

assert.match(nginx, /proxy_cache_valid 200 60s/);
assert.match(nginx, /proxy_cache_lock on/);
assert.match(nginx, /proxy_cache_background_update off/);
assert.match(nginx, /proxy_cache_use_stale off/);
assert.match(nginx, /\$uri\|\$is_args\$args/);
assert.match(nginx, /proxy_set_header Cookie ""/);
assert.match(nginx, /proxy_set_header Authorization ""/);
assert.match(nginx, /limit_req zone=traffic_report_per_ip/);
assert.match(nginx, /traffic_report_kpi_admin_per_ip/);
assert.match(nginx, /location \^~ \/api\/report\/v1\/kpi-admin\//);
assert.match(nginx, /location = \/api\/report\/v1\/kpi-admin\/lock/);
assert.match(nginx, /annual_kpi_admin=locked/);
assert.match(nginx, /location = \/api\/report\/v1\/kpi-config/);
assert.match(nginx, /proxy_set_header Cookie \$http_cookie/);
assert.match(nginx, /location = \/dashboard/);
assert.match(nginx, /server_name report\.ahtops\.xyz/);
assert.match(nginx, /absolute_redirect off/);
assert.match(nginx, /location = \/ \{\s*return 308 \/reports\/traffic;/);
assert.match(nginx, /location = \/reports\/traffic \{/);
assert.match(nginx, /location \/ \{\s*return 404;/);
assert.match(stagingNginx, /listen 127\.0\.0\.1:8781/);
assert.match(stagingNginx, /root \/srv\/seasonal-traffic-report\/staging-current/);
assert.match(stagingNginx, /127\.0\.0\.1:9002\/traffic-report/);
assert.match(stagingNginx, /location = \/api\/report\/v1\/kpi-admin\/lock/);
assert.match(stagingNginx, /annual_kpi_admin=locked/);
assert.match(stagingNginx, /location = \/api\/report\/v1\/kpi-config/);
assert.doesNotMatch(stagingNginx, /127\.0\.0\.1:9001\/traffic-report/);
assert.doesNotMatch(stagingNginx, /root \/srv\/seasonal-traffic-report\/current/);
assert.doesNotMatch(stagingNginx, /proxy_cache_path|limit_req_zone/);
assert.match(stagingTunnel, /--url http:\/\/127\.0\.0\.1:8781/);
assert.doesNotMatch(stagingTunnel, /127\.0\.0\.1:8780/);

assert.match(packageJson, /"build:traffic-report": "node scripts\/build-traffic-report-only\.mjs"/);
assert.match(reportOnlyBuild, /src', 'app', '\(public-report\)'/);
assert.match(reportOnlyBuild, /trafficReportOperationalHours\.ts/);
assert.match(reportOnlyBuild, /trafficReportDataAdapter\.ts/);
assert.match(reportOnlyBuild, /trafficReportV2Contract\.ts/);
assert.doesNotMatch(reportOnlyBuild, /copy\(join\(appRoot, 'src', 'app', '\(desktop\)'/);
assert.match(reportOnlyBuild, /unexpected desktop route/);
assert.match(reportOnlyBuild, /Native app required/);
assert.match(deployRunbook, /app\/out-report/);
assert.match(deployRunbook, /Do not deploy `app\/out`/);
assert.match(deployRunbook, /psql -1 -v ON_ERROR_STOP=1 -f/);
assert.match(deployRunbook, /leave `\/srv\/seasonal-traffic-report\/current` unchanged/);

assert.match(refreshTimer, /keep this timer disabled/);
assert.match(refreshTimer, /OnUnitInactiveSec=5m/);
assert.doesNotMatch(refreshTimer, /OnUnitInactiveSec=20s/);
assert.match(productionRefreshTimer, /OnCalendar=\*:0\/5/);
assert.match(productionRefreshTimer, /runner compares source and projection watermarks/);
assert.doesNotMatch(productionRefreshTimer, /OnUnitInactiveSec/);
assert.match(manualRefresh, /systemctl is-enabled --quiet/);
assert.match(refreshService, /seasonal-traffic-report-refresh/);
assert.match(refreshService, /TimeoutStartSec=300/);
assert.match(refreshRunner, /refresh materialized view concurrently reporting\.public_traffic_effective/i);
assert.match(refreshRunner, /projection_watermark/);
assert.match(refreshRunner, /source_watermark/);
assert.match(refreshRunner, /unchanged source_watermark/);
assert.match(refreshRunner, /mark_public_traffic_projection_fresh_v1/);
assert.match(refreshRunner, /mark_public_traffic_projection_failed_v1/);
assert.match(manualRefresh, /systemctl start "\$service_unit"/);
assert.match(manualRefresh, /snapshot_source_watermark/);
assert.match(manualRefresh, /source_changed_after_refresh/);
assert.match(manualRefresh, /invalid_aircraft_type_snapshot/);
assert.match(manualRefresh, /invalid_aircraft_type_rows/);
assert.match(deployRunbook, /systemctl disable --now seasonal-traffic-report-refresh\.timer/);
assert.match(deployRunbook, /allow the command to finish, then allow another 60 seconds/);

console.log(JSON.stringify({ suite: 'traffic-report-edge-contract', status: 'passed' }));
