create table if not exists reporting.public_traffic_coverage (
  id bigint generated by default as identity primary key,
  from_date date not null,
  to_date date not null,
  status text not null check (status in ('complete', 'partial', 'missing', 'excluded')),
  season_code text,
  source_batch_id text,
  reason_code text,
  certified_at timestamptz,
  certified_by text,
  created_at timestamptz not null default now(),
  check (from_date <= to_date)
);

create index if not exists public_traffic_coverage_range_idx
  on reporting.public_traffic_coverage (from_date, to_date, certified_at desc);

revoke all on reporting.public_traffic_coverage from public, anon, authenticated, service_role;

create or replace function reporting.get_traffic_report_timeline_v2(
  p_from_date date,
  p_to_date date,
  p_window_from date default null,
  p_window_to date default null,
  p_granularity text default 'day',
  p_after_date date default null,
  p_page_size integer default 366,
  p_filters jsonb default '{}'::jsonb,
  p_data_as_of timestamptz default now()
) returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, reporting, public, pg_temp
set statement_timeout = '7s'
as $$
with requested as (
  select greatest(p_from_date, coalesce(p_window_from, p_from_date), coalesce(p_after_date + 1, p_from_date)) as page_from,
    least(p_to_date, coalesce(p_window_to, p_to_date)) as requested_to
), page as (
  select page_from, least(requested_to, page_from + least(greatest(p_page_size, 1), 732) - 1) as page_to, requested_to
  from requested
), spine as (
  select generate_series(page.page_from, page.page_to, interval '1 day')::date as ops_date
  from page
), grouped as (
  select operations.ops_date,
    count(*)::integer as flights,
    count(*) filter (where operations.type = 'A')::integer as arrivals,
    count(*) filter (where operations.type = 'D')::integer as departures,
    coalesce(sum(operations.pax) filter (
      where operations.pax is not null
        and operations.scheduled_local_at + interval '1 day' <= p_data_as_of at time zone 'Asia/Ho_Chi_Minh'
    ), 0)::bigint as reported_pax,
    count(*) filter (
      where operations.pax is not null
        and operations.scheduled_local_at + interval '1 day' <= p_data_as_of at time zone 'Asia/Ho_Chi_Minh'
    )::integer as reported_legs,
    count(*) filter (
      where operations.scheduled_local_at + interval '1 day' <= p_data_as_of at time zone 'Asia/Ho_Chi_Minh'
    )::integer as due_legs
  from reporting.public_traffic_effective operations, page
  where operations.ops_date between page.page_from and page.page_to
    and (not p_filters ? 'types' or operations.type in (select jsonb_array_elements_text(p_filters->'types')))
    and (not p_filters ? 'airlines' or operations.airline in (select jsonb_array_elements_text(p_filters->'airlines')))
    and (not p_filters ? 'routes' or operations.route in (select jsonb_array_elements_text(p_filters->'routes')))
    and (not p_filters ? 'countries' or operations.country in (select jsonb_array_elements_text(p_filters->'countries')))
    and (not p_filters ? 'aircraft_groups' or operations.aircraft_group in (select jsonb_array_elements_text(p_filters->'aircraft_groups')))
  group by operations.ops_date
), coverage as (
  select spine.ops_date,
    coalesce((
      select ledger.status
      from reporting.public_traffic_coverage ledger
      where spine.ops_date between ledger.from_date and ledger.to_date
        and ledger.status <> 'excluded'
      order by ledger.certified_at desc nulls last, ledger.id desc
      limit 1
    ), case when coalesce(grouped.flights, 0) > 0 then 'partial' else 'missing' end) as coverage_status
  from spine
  left join grouped using (ops_date)
), joined as (
  select spine.ops_date,
    coverage.coverage_status,
    case when grouped.flights is not null then grouped.flights when coverage.coverage_status = 'complete' then 0 end as flights,
    case when grouped.arrivals is not null then grouped.arrivals when coverage.coverage_status = 'complete' then 0 end as arrivals,
    case when grouped.departures is not null then grouped.departures when coverage.coverage_status = 'complete' then 0 end as departures,
    case when grouped.reported_legs > 0 then grouped.reported_pax end as reported_pax,
    coalesce(grouped.reported_legs, 0)::integer as reported_legs,
    coalesce(grouped.due_legs, 0)::integer as due_legs
  from spine
  join coverage using (ops_date)
  left join grouped using (ops_date)
), stats as (
  select count(*) filter (where flights between 1 and 2)::integer as small_cells
  from joined
), marked as (
  select joined.*,
    case
      when flights between 1 and 2 then true
      when stats.small_cells = 1 and flights >= 3 and row_number() over (partition by (flights >= 3) order by flights, ops_date) = 1 then true
      else false
    end as suppressed
  from joined cross join stats
)
select jsonb_build_object(
  'page_from', page.page_from,
  'page_to', page.page_to,
  'has_more', page.page_to < page.requested_to,
  'next_cursor', case when page.page_to < page.requested_to then page.page_to::text end,
  'granularity', p_granularity,
  'series', coalesce(jsonb_agg(jsonb_build_object(
    'ops_date', marked.ops_date,
    'flights', case when not marked.suppressed then marked.flights end,
    'arrivals', case when not marked.suppressed and marked.arrivals not between 1 and 2 and marked.departures not between 1 and 2 then marked.arrivals end,
    'departures', case when not marked.suppressed and marked.arrivals not between 1 and 2 and marked.departures not between 1 and 2 then marked.departures end,
    'reported_pax', case when not marked.suppressed and marked.reported_legs not between 1 and 2 then marked.reported_pax end,
    'reported_legs', case when not marked.suppressed and marked.due_legs >= 3 and marked.reported_legs not between 1 and 2 then marked.reported_legs end,
    'due_legs', case when not marked.suppressed and marked.due_legs >= 3 then marked.due_legs end,
    'pax_coverage_pct', case when not marked.suppressed and marked.due_legs >= 3 and marked.reported_legs not between 1 and 2 then round(marked.reported_legs * 100.0 / nullif(marked.due_legs, 0), 1) end,
    'pax_status', case
      when marked.suppressed or marked.reported_legs between 1 and 2 or marked.due_legs between 1 and 2 then 'suppressed'
      when marked.due_legs = 0 then 'not_due'
      when marked.reported_legs = 0 then 'unavailable'
      else 'available'
    end,
    'suppressed', marked.suppressed,
    'status', case
      when marked.suppressed then 'suppressed'
      when marked.coverage_status = 'missing' then 'missing'
      when marked.coverage_status = 'partial' then 'partial'
      when marked.ops_date > ((p_data_as_of at time zone 'Asia/Ho_Chi_Minh')::date - case when (p_data_as_of at time zone 'Asia/Ho_Chi_Minh')::time < time '05:00' then 1 else 0 end) then 'future'
      when marked.flights = 0 then 'zero'
      else 'complete'
    end,
    'completeness', marked.coverage_status
  ) order by marked.ops_date), '[]'::jsonb)
)
from page left join marked on true
group by page.page_from, page.page_to, page.requested_to;
$$;

create or replace function reporting.get_traffic_report_monthly_peaks_v2(
  p_from_date date,
  p_to_date date,
  p_filters jsonb default '{}'::jsonb,
  p_time_basis text default 'local'
) returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, reporting, public, pg_temp
set statement_timeout = '5s'
as $$
with filtered as (
  select operations.*,
    date_trunc('month', operations.ops_date)::date as month_start,
    case when p_time_basis = 'utc' then operations.utc_minutes / 60 else operations.local_minutes / 60 end as hour_index
  from reporting.public_traffic_effective operations
  where operations.ops_date between p_from_date and p_to_date
    and (not p_filters ? 'types' or operations.type in (select jsonb_array_elements_text(p_filters->'types')))
    and (not p_filters ? 'airlines' or operations.airline in (select jsonb_array_elements_text(p_filters->'airlines')))
    and (not p_filters ? 'routes' or operations.route in (select jsonb_array_elements_text(p_filters->'routes')))
    and (not p_filters ? 'countries' or operations.country in (select jsonb_array_elements_text(p_filters->'countries')))
    and (not p_filters ? 'aircraft_groups' or operations.aircraft_group in (select jsonb_array_elements_text(p_filters->'aircraft_groups')))
), counts as (
  select month_start, type, hour_index, count(*)::integer as flights
  from filtered
  where type in ('A', 'D') and hour_index is not null
  group by month_start, type, hour_index
), ranked as (
  select counts.*, row_number() over (partition by month_start, type order by flights desc, hour_index) as rank
  from counts
), months as (
  select generate_series(date_trunc('month', p_from_date::timestamp), date_trunc('month', p_to_date::timestamp), interval '1 month')::date as month_start
)
select coalesce(jsonb_agg(jsonb_build_object(
  'month', to_char(months.month_start, 'YYYY-MM'),
  'time_basis', p_time_basis,
  'arrival_hour', case when arrivals.flights >= 3 then lpad(arrivals.hour_index::text, 2, '0') || ':00' end,
  'arrival_flights', case when arrivals.flights >= 3 then arrivals.flights end,
  'departure_hour', case when departures.flights >= 3 then lpad(departures.hour_index::text, 2, '0') || ':00' end,
  'departure_flights', case when departures.flights >= 3 then departures.flights end,
  'arrival_suppressed', coalesce(arrivals.flights between 1 and 2, false),
  'departure_suppressed', coalesce(departures.flights between 1 and 2, false)
) order by months.month_start), '[]'::jsonb)
from months
left join ranked arrivals on arrivals.month_start = months.month_start and arrivals.type = 'A' and arrivals.rank = 1
left join ranked departures on departures.month_start = months.month_start and departures.type = 'D' and departures.rank = 1;
$$;

create or replace function public.get_public_traffic_report_dimension_v2(
  p_from_date date,
  p_to_date date,
  p_dimension text,
  p_types text[] default array['A', 'D']::text[],
  p_airlines text[] default array[]::text[],
  p_routes text[] default array[]::text[],
  p_countries text[] default array[]::text[],
  p_sort text default 'flights',
  p_page integer default 1,
  p_page_size integer default 50,
  p_data_as_of timestamptz default now()
) returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, reporting, public, pg_temp
set statement_timeout = '7s'
as $$
declare
  v_result jsonb;
begin
  if p_from_date is null or p_to_date is null or p_from_date > p_to_date then raise exception 'invalid date range' using errcode = '22023'; end if;
  if p_dimension not in ('route', 'country', 'airline') then raise exception 'invalid dimension' using errcode = '22023'; end if;
  if p_types <@ array['A', 'D']::text[] is not true or cardinality(p_types) = 0 then raise exception 'invalid types' using errcode = '22023'; end if;
  if p_sort not in ('flights', 'reported_pax', 'flight_share', 'pax_share', 'label') then raise exception 'invalid sort' using errcode = '22023'; end if;
  if p_page < 1 or p_page_size < 1 or p_page_size > 732 then raise exception 'invalid page' using errcode = '22023'; end if;
  if cardinality(p_airlines) > 24 or cardinality(p_routes) > 24 or cardinality(p_countries) > 24 then raise exception 'filter cardinality exceeds 24' using errcode = '54000'; end if;

  with filtered as materialized (
    select operations.*
    from reporting.public_traffic_effective operations
    where operations.ops_date between p_from_date and p_to_date
      and operations.type = any(p_types)
      and (cardinality(p_airlines) = 0 or operations.airline = any(p_airlines))
      and (cardinality(p_routes) = 0 or operations.route = any(p_routes))
      and (cardinality(p_countries) = 0 or operations.country = any(p_countries))
  ), grouped as (
    select case p_dimension when 'route' then route when 'country' then country else airline end as label,
      count(*)::integer as flights,
      count(*) filter (where type = 'A')::integer as arrivals,
      count(*) filter (where type = 'D')::integer as departures,
      coalesce(sum(pax) filter (
        where pax is not null
          and scheduled_local_at + interval '1 day' <= p_data_as_of at time zone 'Asia/Ho_Chi_Minh'
      ), 0)::bigint as reported_pax,
      count(*) filter (
        where pax is not null
          and scheduled_local_at + interval '1 day' <= p_data_as_of at time zone 'Asia/Ho_Chi_Minh'
      )::integer as reported_legs,
      count(*) filter (
        where scheduled_local_at + interval '1 day' <= p_data_as_of at time zone 'Asia/Ho_Chi_Minh'
      )::integer as due_legs
    from filtered
    group by case p_dimension when 'route' then route when 'country' then country else airline end
  ), privacy_bucketed as (
    select case when flights < 3 then 'Khác' else coalesce(nullif(label, ''), 'Unknown') end as label,
      sum(flights)::integer as flights,
      sum(arrivals)::integer as arrivals,
      sum(departures)::integer as departures,
      sum(reported_pax)::bigint as reported_pax,
      sum(reported_legs)::integer as reported_legs,
      sum(due_legs)::integer as due_legs
    from grouped
    group by case when flights < 3 then 'Khác' else coalesce(nullif(label, ''), 'Unknown') end
  ), totals as (
    select coalesce(sum(flights), 0)::integer as total_flights,
      coalesce(sum(reported_pax), 0)::bigint as total_reported_pax
    from privacy_bucketed
  ), marked as (
    select privacy_bucketed.*,
      count(*) filter (where flights between 1 and 2) over () as small_count,
      row_number() over (partition by flights >= 3 order by flights, label) as visible_rank
    from privacy_bucketed
  ), publishable as (
    select marked.*, totals.total_flights, totals.total_reported_pax,
      flights between 1 and 2 or (small_count = 1 and flights >= 3 and visible_rank = 1) as suppressed,
      reported_legs between 1 and 2 as pax_suppressed
    from marked cross join totals
  ), ordered as (
    select publishable.*,
      row_number() over (order by
        case when p_sort in ('flights', 'flight_share') then flights end desc,
        case when p_sort in ('reported_pax', 'pax_share') then reported_pax end desc,
        label asc
      ) as row_number,
      count(*) over ()::integer as total_rows
    from publishable
  ), paged as (
    select * from ordered
    where row_number > (p_page - 1) * p_page_size
      and row_number <= p_page * p_page_size
  )
  select jsonb_build_object(
    'dimension', p_dimension,
    'type', case when p_types = array['A']::text[] then 'A' when p_types = array['D']::text[] then 'D' else 'all' end,
    'page', p_page,
    'page_size', p_page_size,
    'total_rows', coalesce((select max(total_rows) from ordered), 0),
    'has_more', coalesce((select max(total_rows) from ordered), 0) > p_page * p_page_size,
    'rows', coalesce((select jsonb_agg(jsonb_build_object(
      'key', lower(replace(label, ' ', '-')),
      'label', label,
      'flights', case when not suppressed then flights end,
      'arrivals', case when not suppressed and arrivals not between 1 and 2 and departures not between 1 and 2 then arrivals end,
      'departures', case when not suppressed and arrivals not between 1 and 2 and departures not between 1 and 2 then departures end,
      'reported_pax', case when not suppressed and not pax_suppressed and reported_legs > 0 then reported_pax end,
      'reported_legs', case when not suppressed and not pax_suppressed and due_legs >= 3 then reported_legs end,
      'due_legs', case when not suppressed and due_legs >= 3 then due_legs end,
      'pax_coverage_pct', case when not suppressed and not pax_suppressed and due_legs >= 3 then round(reported_legs * 100.0 / nullif(due_legs, 0), 1) end,
      'flight_share', case when not suppressed then flights::numeric / nullif(total_flights, 0) end,
      'pax_share', case when not suppressed and not pax_suppressed and reported_legs > 0 then reported_pax::numeric / nullif(total_reported_pax, 0) end,
      'suppressed', suppressed,
      'pax_status', case when suppressed or pax_suppressed then 'suppressed' when due_legs = 0 then 'not_due' when reported_legs = 0 then 'unavailable' else 'available' end
    ) order by row_number) from paged), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

create or replace function public.get_public_traffic_report_overview_v1(
  p_from_date date default null,
  p_to_date date default null,
  p_types text[] default array['A', 'D']::text[],
  p_airlines text[] default array[]::text[],
  p_routes text[] default array[]::text[],
  p_countries text[] default array[]::text[],
  p_aircraft_groups text[] default array[]::text[],
  p_comparison text default 'previous_period',
  p_time_basis text default 'local',
  p_timeline_after date default null,
  p_timeline_page_size integer default 366,
  p_contract_version text default 'traffic-report-v1'
) returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, reporting, public, pg_temp
set statement_timeout = '9s'
as $$
declare
  v_min_date date;
  v_max_date date;
  v_completed_date date;
  v_from_date date;
  v_to_date date;
  v_data_as_of timestamptz;
  v_filters jsonb;
  v_filter_options jsonb;
  v_coverage jsonb;
  v_request jsonb;
  v_request_hash text;
  v_kpis jsonb;
  v_timeline jsonb;
  v_breakdowns jsonb;
  v_watermark bigint;
begin
  if p_contract_version <> 'traffic-report-v1' then raise exception 'unsupported contract_version' using errcode = '22023'; end if;
  if (p_from_date is null) <> (p_to_date is null) then raise exception 'from_date and to_date must be provided together' using errcode = '22023'; end if;
  if p_comparison not in ('previous_period', 'previous_year', 'none') then raise exception 'invalid comparison' using errcode = '22023'; end if;
  if p_time_basis not in ('local', 'utc') then raise exception 'invalid time_basis' using errcode = '22023'; end if;
  if p_types <@ array['A', 'D']::text[] is not true or cardinality(p_types) = 0 then raise exception 'invalid types' using errcode = '22023'; end if;
  if cardinality(p_airlines) > 24 or cardinality(p_routes) > 24 or cardinality(p_countries) > 24 or cardinality(p_aircraft_groups) > 24 then raise exception 'filter cardinality exceeds 24' using errcode = '54000'; end if;

  select min(ops_date), max(ops_date), max(snapshot_refreshed_at), max(snapshot_source_watermark)
    into v_min_date, v_max_date, v_data_as_of, v_watermark
  from reporting.public_traffic_effective;
  if v_min_date is null or v_max_date is null then raise exception 'traffic report has no effective operations' using errcode = 'P0002'; end if;
  v_completed_date := (v_data_as_of at time zone 'Asia/Ho_Chi_Minh')::date
    - case when (v_data_as_of at time zone 'Asia/Ho_Chi_Minh')::time < time '05:00' then 2 else 1 end;
  v_from_date := coalesce(p_from_date, greatest(v_min_date, make_date(extract(year from v_completed_date)::integer, 1, 1)));
  v_to_date := coalesce(p_to_date, least(v_max_date, v_completed_date));
  if v_to_date < v_from_date and p_from_date is null then v_from_date := v_min_date; v_to_date := v_min_date; end if;
  if v_from_date > v_to_date then raise exception 'from_date must not exceed to_date' using errcode = '22023'; end if;
  if v_from_date < v_min_date or v_to_date > v_max_date then raise exception 'date range is outside available Ops Date domain' using errcode = '22023'; end if;

  v_filters := jsonb_strip_nulls(jsonb_build_object(
    'types', to_jsonb((select array_agg(distinct upper(value) order by upper(value)) from unnest(p_types) value)),
    'airlines', case when cardinality(p_airlines) > 0 then to_jsonb((select array_agg(distinct upper(value) order by upper(value)) from unnest(p_airlines) value)) end,
    'routes', case when cardinality(p_routes) > 0 then to_jsonb((select array_agg(distinct upper(value) order by upper(value)) from unnest(p_routes) value)) end,
    'countries', case when cardinality(p_countries) > 0 then to_jsonb((select array_agg(distinct value order by value) from unnest(p_countries) value)) end,
    'aircraft_groups', case when cardinality(p_aircraft_groups) > 0 then to_jsonb((select array_agg(distinct value order by value) from unnest(p_aircraft_groups) value)) end
  ));
  v_request := jsonb_build_object('from', v_from_date, 'to', v_to_date, 'filters', v_filters, 'comparison', p_comparison, 'time_basis', p_time_basis, 'contract_version', p_contract_version);
  v_request_hash := encode(extensions.digest(convert_to(v_request::text, 'UTF8'), 'sha256'), 'hex');
  v_kpis := reporting.get_traffic_report_kpis(v_from_date, v_to_date, v_filters, p_comparison, v_data_as_of);
  if coalesce(v_kpis#>>'{current,reported_pax}', '') = '0' then
    v_kpis := jsonb_set(v_kpis, '{current,reported_pax}', 'null'::jsonb);
  end if;
  if coalesce(v_kpis#>>'{comparison,reported_pax}', '') = '0' then
    v_kpis := jsonb_set(v_kpis, '{comparison,reported_pax}', 'null'::jsonb);
  end if;
  v_timeline := reporting.get_traffic_report_timeline_v2(v_from_date, v_to_date, null, null, 'day', p_timeline_after, p_timeline_page_size, v_filters, v_data_as_of);
  v_breakdowns := reporting.get_traffic_report_breakdowns(v_from_date, v_to_date, v_filters, 10, p_time_basis, 60, v_data_as_of)
    || jsonb_build_object('peak_hour_monthly', reporting.get_traffic_report_monthly_peaks_v2(v_from_date, v_to_date, v_filters, p_time_basis));

  with dates as (
    select generate_series(v_from_date, v_to_date, interval '1 day')::date as ops_date
  ), statuses as (
    select dates.ops_date,
      coalesce((select ledger.status from reporting.public_traffic_coverage ledger
        where dates.ops_date between ledger.from_date and ledger.to_date and ledger.status <> 'excluded'
        order by ledger.certified_at desc nulls last, ledger.id desc limit 1),
        case when exists(select 1 from reporting.public_traffic_effective operations where operations.ops_date = dates.ops_date) then 'partial' else 'missing' end
      ) as status
    from dates
  )
  select jsonb_build_object(
    'selected_day_count', count(*),
    'covered_day_count', count(*) filter (where status = 'complete'),
    'partial_day_count', count(*) filter (where status = 'partial'),
    'missing_day_count', count(*) filter (where status = 'missing')
  ) into v_coverage from statuses;

  select jsonb_build_object(
    'airline', coalesce((select jsonb_agg(label order by label) from (
      select airline as label from reporting.public_traffic_effective where airline <> '' group by airline having count(*) >= 3 order by airline limit 250
    ) options), '[]'::jsonb),
    'route', coalesce((select jsonb_agg(label order by label) from (
      select route as label from reporting.public_traffic_effective where route <> '' group by route having count(*) >= 3 order by route limit 250
    ) options), '[]'::jsonb),
    'country', coalesce((select jsonb_agg(label order by label) from (
      select country as label from reporting.public_traffic_effective where country <> '' group by country having count(*) >= 3 order by country limit 250
    ) options), '[]'::jsonb)
  ) into v_filter_options;

  return jsonb_build_object(
    'contract_version', p_contract_version,
    'request_hash', v_request_hash,
    'data_as_of', v_data_as_of,
    'source_watermark', coalesce(to_jsonb(v_watermark), to_jsonb('unknown'::text)),
    'metadata', jsonb_build_object(
      'min_ops_date', v_min_date,
      'max_ops_date', v_max_date,
      'latest_completed_ops_date', least(v_max_date, v_completed_date),
      'normalized_filter', jsonb_build_object(
        'from', v_from_date, 'to', v_to_date,
        'type', case when p_types = array['A']::text[] then 'A' when p_types = array['D']::text[] then 'D' else 'all' end,
        'airline', coalesce(v_filters->'airlines', '[]'::jsonb),
        'route', coalesce(v_filters->'routes', '[]'::jsonb),
        'country', coalesce(v_filters->'countries', '[]'::jsonb),
        'comp', case p_comparison when 'previous_year' then 'year_ago' when 'none' then 'none' else 'previous' end,
        'tz', p_time_basis
      ),
      'filter_options', v_filter_options,
      'filter_options_limit', 250,
      'available_dimensions', jsonb_build_array('route', 'country', 'airline'),
      'day_count', v_to_date - v_from_date + 1,
      'selected_day_count', (v_coverage->>'selected_day_count')::integer,
      'covered_day_count', (v_coverage->>'covered_day_count')::integer,
      'partial_day_count', (v_coverage->>'partial_day_count')::integer,
      'missing_day_count', (v_coverage->>'missing_day_count')::integer,
      'timeline_granularity', 'day',
      'timeline_has_more', coalesce((v_timeline->>'has_more')::boolean, false),
      'timeline_next_cursor', v_timeline->>'next_cursor',
      'suppression_policy', jsonb_build_object('threshold', 3, 'applied', true)
    ),
    'kpis', jsonb_set(v_kpis - 'quality', '{current,status}', to_jsonb(case
      when (v_coverage->>'missing_day_count')::integer > 0 or (v_coverage->>'partial_day_count')::integer > 0 then 'partial'
      else coalesce(v_kpis#>>'{current,status}', 'complete') end)),
    'timeline', coalesce(v_timeline->'series', '[]'::jsonb),
    'breakdowns', v_breakdowns,
    'quality', coalesce(v_kpis->'quality', '{}'::jsonb) || jsonb_build_object(
      'notes', jsonb_build_array(
        'Pax chỉ cộng số đã báo cáo trên các chuyến đã đến hạn.',
        'Ngày chưa được xác nhận đầy đủ không được tự động xem là sản lượng bằng 0.',
        'Quốc gia lấy từ database; tuyến chưa mapping thuộc nhóm Unknown.'
      )
    )
  );
end;
$$;

alter function reporting.get_traffic_report_timeline_v2(date, date, date, date, text, date, integer, jsonb, timestamptz) owner to postgres;
alter function reporting.get_traffic_report_monthly_peaks_v2(date, date, jsonb, text) owner to postgres;
alter function public.get_public_traffic_report_dimension_v2(date, date, text, text[], text[], text[], text[], text, integer, integer, timestamptz) owner to postgres;
alter function public.get_public_traffic_report_overview_v1(date, date, text[], text[], text[], text[], text[], text, text, date, integer, text) owner to postgres;

revoke execute on function reporting.get_traffic_report_timeline_v2(date, date, date, date, text, date, integer, jsonb, timestamptz) from public, anon, authenticated, service_role;
revoke execute on function reporting.get_traffic_report_monthly_peaks_v2(date, date, jsonb, text) from public, anon, authenticated, service_role;
revoke execute on function public.get_public_traffic_report_dimension_v2(date, date, text, text[], text[], text[], text[], text, integer, integer, timestamptz) from public, anon, authenticated;
revoke execute on function public.get_public_traffic_report_overview_v1(date, date, text[], text[], text[], text[], text[], text, text, date, integer, text) from public, anon, authenticated;

grant execute on function public.get_public_traffic_report_dimension_v2(date, date, text, text[], text[], text[], text[], text, integer, integer, timestamptz) to service_role;
grant execute on function public.get_public_traffic_report_overview_v1(date, date, text[], text[], text[], text[], text[], text, text, date, integer, text) to service_role;
